//! Code Orchestration types for Programmatic Tool Calling
//!
//! Defines types for LLM-generated code that programmatically orchestrates
//! tool calls (loops, conditions, error handling) via a sandbox execution
//! environment with an HTTP tool proxy bridge.

use serde::{Deserialize, Serialize};
use std::time::Duration;

/// Request to execute code orchestration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CodeOrchestrationRequest {
    /// The code to execute (generated by LLM)
    pub code: String,
    /// Programming language ("python" or "javascript")
    #[serde(default = "default_language")]
    pub language: String,
    /// References to prior step outputs to inject as context
    #[serde(default)]
    pub context_refs: Vec<String>,
    /// Context data from prior steps (resolved from context_refs)
    #[serde(default)]
    pub context_data: serde_json::Value,
    /// Execution timeout
    #[serde(default = "default_timeout")]
    pub timeout: Duration,
}

fn default_language() -> String {
    "python".to_string()
}

fn default_timeout() -> Duration {
    Duration::from_secs(300)
}

impl CodeOrchestrationRequest {
    /// Create a new Python code orchestration request
    pub fn python(code: impl Into<String>) -> Self {
        Self {
            code: code.into(),
            language: "python".to_string(),
            context_refs: Vec::new(),
            context_data: serde_json::Value::Null,
            timeout: default_timeout(),
        }
    }

    /// Create a new JavaScript code orchestration request
    pub fn javascript(code: impl Into<String>) -> Self {
        Self {
            code: code.into(),
            language: "javascript".to_string(),
            context_refs: Vec::new(),
            context_data: serde_json::Value::Null,
            timeout: default_timeout(),
        }
    }

    /// Set context data
    pub fn with_context(mut self, context: serde_json::Value) -> Self {
        self.context_data = context;
        self
    }

    /// Set timeout
    pub fn with_timeout(mut self, timeout: Duration) -> Self {
        self.timeout = timeout;
        self
    }
}

/// Result of a code orchestration execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CodeOrchestrationResult {
    /// Whether the execution succeeded
    pub success: bool,
    /// Return value (parsed from stdout if JSON)
    #[serde(default)]
    pub return_value: Option<serde_json::Value>,
    /// Raw stdout from the execution
    pub stdout: String,
    /// Raw stderr from the execution
    pub stderr: String,
    /// Exit code
    pub exit_code: i32,
    /// Records of all tool calls made during execution
    pub tool_calls: Vec<ToolCallRecord>,
    /// Total execution duration in milliseconds
    pub duration_ms: u64,
    /// Error message if execution failed
    #[serde(default)]
    pub error: Option<String>,
}

/// Record of a single tool call made by the sandbox code
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolCallRecord {
    /// Tool name that was called
    pub tool_name: String,
    /// Arguments passed to the tool
    pub arguments: serde_json::Value,
    /// Result returned by the tool
    #[serde(default)]
    pub result: Option<serde_json::Value>,
    /// Error if the tool call failed
    #[serde(default)]
    pub error: Option<String>,
    /// Duration of the tool call in milliseconds
    pub duration_ms: u64,
    /// Timestamp of the call
    pub timestamp: chrono::DateTime<chrono::Utc>,
}

impl ToolCallRecord {
    /// Create a new successful tool call record
    pub fn success(
        tool_name: impl Into<String>,
        arguments: serde_json::Value,
        result: serde_json::Value,
        duration_ms: u64,
    ) -> Self {
        Self {
            tool_name: tool_name.into(),
            arguments,
            result: Some(result),
            error: None,
            duration_ms,
            timestamp: chrono::Utc::now(),
        }
    }

    /// Create a new failed tool call record
    pub fn failure(
        tool_name: impl Into<String>,
        arguments: serde_json::Value,
        error: impl Into<String>,
        duration_ms: u64,
    ) -> Self {
        Self {
            tool_name: tool_name.into(),
            arguments,
            result: None,
            error: Some(error.into()),
            duration_ms,
            timestamp: chrono::Utc::now(),
        }
    }
}

/// Configuration for code orchestration
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CodeOrchestrationConfig {
    /// Whether code orchestration is enabled
    #[serde(default = "default_enabled")]
    pub enabled: bool,
    /// Default execution timeout
    #[serde(default = "default_timeout")]
    pub default_timeout: Duration,
    /// Maximum number of tool calls allowed in a single execution
    #[serde(default = "default_max_tool_calls")]
    pub max_tool_calls: usize,
    /// Docker image to use for Python execution
    #[serde(default = "default_python_image")]
    pub python_image: String,
    /// Docker image to use for JavaScript execution
    #[serde(default = "default_js_image")]
    pub js_image: String,
    /// Whether to allow network access from the sandbox (for tool proxy)
    #[serde(default = "default_allow_network")]
    pub allow_network: bool,
}

fn default_enabled() -> bool {
    false
}

fn default_max_tool_calls() -> usize {
    100
}

fn default_python_image() -> String {
    "python:3.11-slim".to_string()
}

fn default_js_image() -> String {
    "node:20-slim".to_string()
}

fn default_allow_network() -> bool {
    true // Needed for tool proxy bridge
}

impl Default for CodeOrchestrationConfig {
    fn default() -> Self {
        Self {
            enabled: default_enabled(),
            default_timeout: default_timeout(),
            max_tool_calls: default_max_tool_calls(),
            python_image: default_python_image(),
            js_image: default_js_image(),
            allow_network: default_allow_network(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_code_orchestration_request_python() {
        let req = CodeOrchestrationRequest::python("print('hello')")
            .with_context(serde_json::json!({"key": "value"}))
            .with_timeout(Duration::from_secs(60));

        assert_eq!(req.language, "python");
        assert_eq!(req.code, "print('hello')");
        assert_eq!(req.timeout, Duration::from_secs(60));
    }

    #[test]
    fn test_code_orchestration_request_javascript() {
        let req = CodeOrchestrationRequest::javascript("console.log('hello')");

        assert_eq!(req.language, "javascript");
        assert_eq!(req.code, "console.log('hello')");
    }

    #[test]
    fn test_tool_call_record_success() {
        let record = ToolCallRecord::success(
            "Read",
            serde_json::json!({"file_path": "/tmp/test.txt"}),
            serde_json::json!({"content": "hello"}),
            50,
        );

        assert_eq!(record.tool_name, "Read");
        assert!(record.result.is_some());
        assert!(record.error.is_none());
        assert_eq!(record.duration_ms, 50);
    }

    #[test]
    fn test_tool_call_record_failure() {
        let record = ToolCallRecord::failure(
            "Read",
            serde_json::json!({"file_path": "/nonexistent"}),
            "File not found",
            10,
        );

        assert_eq!(record.tool_name, "Read");
        assert!(record.result.is_none());
        assert_eq!(record.error, Some("File not found".to_string()));
    }

    #[test]
    fn test_code_orchestration_config_defaults() {
        let config = CodeOrchestrationConfig::default();

        assert!(!config.enabled);
        assert_eq!(config.default_timeout, Duration::from_secs(300));
        assert_eq!(config.max_tool_calls, 100);
        assert!(config.allow_network);
    }

    #[test]
    fn test_code_orchestration_result_serialization() {
        let result = CodeOrchestrationResult {
            success: true,
            return_value: Some(serde_json::json!(["file1.rs", "file2.rs"])),
            stdout: "[\"file1.rs\", \"file2.rs\"]".to_string(),
            stderr: String::new(),
            exit_code: 0,
            tool_calls: vec![],
            duration_ms: 1500,
            error: None,
        };

        let json = serde_json::to_string(&result).unwrap();
        let deserialized: CodeOrchestrationResult = serde_json::from_str(&json).unwrap();

        assert!(deserialized.success);
        assert_eq!(deserialized.exit_code, 0);
        assert_eq!(deserialized.duration_ms, 1500);
    }
}
