//! Adapters for integrating existing components with the StateGraph engine.
//!
//! This module provides adapters that wrap existing Canal components
//! (AgentRunner, LlmRouter, ToolRegistry) as StateGraph nodes.
//!
//! # Key Adapters
//!
//! - [`AgentRunnerNode`] - Wraps AgentRunner as a NodeHandler
//! - [`AgentGraphState`] - Standard graph state for agent workflows
//! - [`LlmCallNode`] - Single LLM call node
//! - [`ToolCallNode`] - Single tool call node

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Duration;

use async_trait::async_trait;
use futures::StreamExt;
use serde::{Deserialize, Serialize};

use super::error::NodeError;
use super::node::{NodeContext, NodeHandler};
use super::GraphState;
use crate::agent::factory::AgentFactory;
use crate::agent::r#loop::{AgentLoop, AgentRunner};
use crate::agent::types::{AgentMessage, ContentBlock, Usage};

/// Standard graph state for agent workflows.
///
/// This state type can be used with any graph-based agent execution. It contains
/// the conversation history, current task, results, and metadata.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AgentGraphState {
    /// Conversation messages accumulated during execution.
    pub messages: Vec<AgentMessage>,
    /// The current task or prompt being processed.
    pub task: String,
    /// Results from previous steps (keyed by step/node name).
    pub step_results: HashMap<String, serde_json::Value>,
    /// Working memory for passing data between nodes.
    pub working_memory: HashMap<String, serde_json::Value>,
    /// Execution metadata.
    pub metadata: StateMetadata,
    /// Error state if execution failed.
    pub error: Option<String>,
    /// Final response text (accumulated from assistant messages).
    pub response: String,
    /// Plan generated by the planner node (for PlanExecute mode).
    #[serde(default)]
    pub plan: Option<String>,
    /// Execution result from the executor node (for PlanExecute mode).
    #[serde(default)]
    pub execution_result: Option<String>,
}

impl AgentGraphState {
    /// Create a new state with a task.
    pub fn new(task: impl Into<String>) -> Self {
        Self {
            messages: Vec::new(),
            task: task.into(),
            step_results: HashMap::new(),
            working_memory: HashMap::new(),
            metadata: StateMetadata::default(),
            error: None,
            response: String::new(),
            plan: None,
            execution_result: None,
        }
    }

    /// Add a message to the conversation.
    pub fn add_message(&mut self, msg: AgentMessage) {
        // Extract text content from assistant messages into response
        if let AgentMessage::Assistant(assistant_msg) = &msg {
            for block in &assistant_msg.content {
                if let ContentBlock::Text { text } = block {
                    if !self.response.is_empty() {
                        self.response.push('\n');
                    }
                    self.response.push_str(text);
                }
            }
        }
        self.messages.push(msg);
    }

    /// Get the last response text.
    pub fn get_response(&self) -> &str {
        &self.response
    }

    /// Set an error.
    pub fn with_error(mut self, error: impl Into<String>) -> Self {
        self.error = Some(error.into());
        self
    }

    /// Store a step result.
    pub fn set_step_result(&mut self, step: impl Into<String>, value: serde_json::Value) {
        self.step_results.insert(step.into(), value);
    }

    /// Get a step result.
    pub fn get_step_result(&self, step: &str) -> Option<&serde_json::Value> {
        self.step_results.get(step)
    }

    /// Store a working memory value.
    pub fn set_memory(&mut self, key: impl Into<String>, value: serde_json::Value) {
        self.working_memory.insert(key.into(), value);
    }

    /// Get a working memory value.
    pub fn get_memory(&self, key: &str) -> Option<&serde_json::Value> {
        self.working_memory.get(key)
    }

    /// Check if execution has failed.
    pub fn has_error(&self) -> bool {
        self.error.is_some()
    }

    /// Get the typed PlanExecute state overlay.
    ///
    /// Returns a deserialized `PlanExecuteState` from the reserved working memory key.
    /// If no state exists yet, returns a default instance.
    #[cfg(feature = "collaboration")]
    pub fn plan_state(&self) -> crate::collaboration::state::PlanExecuteState {
        self.working_memory
            .get(crate::collaboration::state::PLAN_STATE_KEY)
            .and_then(|v| serde_json::from_value(v.clone()).ok())
            .unwrap_or_default()
    }

    /// Update the typed PlanExecute state overlay via a closure.
    ///
    /// Deserializes the current state (or default), applies the closure,
    /// then serializes it back into working memory.
    ///
    /// # Example
    ///
    /// ```ignore
    /// state.update_plan_state(|ps| {
    ///     ps.current_step_index += 1;
    ///     ps.phase = PipelinePhase::Execution;
    /// });
    /// ```
    #[cfg(feature = "collaboration")]
    pub fn update_plan_state(
        &mut self,
        f: impl FnOnce(&mut crate::collaboration::state::PlanExecuteState),
    ) {
        let mut ps = self.plan_state();
        f(&mut ps);
        if let Ok(v) = serde_json::to_value(&ps) {
            self.working_memory
                .insert(crate::collaboration::state::PLAN_STATE_KEY.to_string(), v);
        }
    }
}

impl GraphState for AgentGraphState {
    fn merge(&mut self, other: Self) {
        // Merge messages (append — no dedup since messages are ordered by time)
        for msg in other.messages {
            self.messages.push(msg);
        }
        // Merge step results (preserve existing — each branch keeps its own results)
        for (k, v) in other.step_results {
            self.step_results.entry(k).or_insert(v);
        }
        // Merge working memory (preserve existing keys)
        for (k, v) in other.working_memory {
            self.working_memory.entry(k).or_insert(v);
        }
        // Merge metadata (accumulate tokens and cost)
        self.metadata.total_tokens += other.metadata.total_tokens;
        self.metadata.total_cost_usd += other.metadata.total_cost_usd;
        // Concatenate responses
        if !other.response.is_empty() {
            if !self.response.is_empty() {
                self.response.push('\n');
            }
            self.response.push_str(&other.response);
        }
        // Take error if we don't have one
        if self.error.is_none() && other.error.is_some() {
            self.error = other.error;
        }
    }
}

/// Metadata for tracking execution statistics.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct StateMetadata {
    /// Total tokens used across all LLM calls.
    pub total_tokens: u32,
    /// Total cost in USD.
    pub total_cost_usd: f64,
    /// Models used during execution.
    pub models_used: Vec<String>,
    /// Start time (as Unix timestamp).
    pub started_at: Option<i64>,
    /// End time (as Unix timestamp).
    pub ended_at: Option<i64>,
}

impl StateMetadata {
    /// Record usage from an LLM call.
    pub fn record_usage(&mut self, usage: &Usage, model: &str) {
        self.total_tokens += usage.input_tokens + usage.output_tokens;
        if !self.models_used.contains(&model.to_string()) {
            self.models_used.push(model.to_string());
        }
    }

    /// Set the start time to now.
    pub fn mark_start(&mut self) {
        self.started_at = Some(chrono::Utc::now().timestamp());
    }

    /// Set the end time to now.
    pub fn mark_end(&mut self) {
        self.ended_at = Some(chrono::Utc::now().timestamp());
    }

    /// Get duration in milliseconds (if both start and end are set).
    pub fn duration_ms(&self) -> Option<i64> {
        match (self.started_at, self.ended_at) {
            (Some(start), Some(end)) => Some((end - start) * 1000),
            _ => None,
        }
    }
}

/// Wraps an AgentRunner as a NodeHandler for use in StateGraphs.
///
/// This adapter allows the existing AgentRunner to be used as a node in
/// a StateGraph execution. It creates a runner from the factory, executes
/// the query from state.task, and collects results back into the state.
///
/// # Example
///
/// ```ignore
/// use gateway_core::graph::adapters::{AgentRunnerNode, AgentGraphState};
/// use gateway_core::graph::StateGraphBuilder;
///
/// let node = AgentRunnerNode::new(factory.clone());
///
/// let graph = StateGraphBuilder::new()
///     .add_node("agent", node)
///     .set_entry("agent")
///     .set_terminal("agent")
///     .build()?;
///
/// let state = AgentGraphState::new("Write a poem about Rust");
/// let result = executor.execute(state).await?;
/// println!("{}", result.response);
/// ```
pub struct AgentRunnerNode {
    /// Factory for creating AgentRunner instances.
    factory: Arc<AgentFactory>,
    /// Session ID prefix for created agents.
    session_id_prefix: String,
    /// Model override (if any).
    model: Option<String>,
    /// Maximum turns for the agent.
    max_turns: u32,
    /// Profile ID for model routing.
    profile_id: Option<String>,
    /// Task type hint for routing.
    task_type: Option<String>,
    /// Optional channel for streaming content events (thinking, text, tool calls)
    /// during graph execution. When set, AgentMessage content blocks are forwarded
    /// as GraphStreamEvent variants in real-time.
    content_tx: Option<tokio::sync::mpsc::Sender<super::GraphStreamEvent>>,
}

impl AgentRunnerNode {
    /// Create a new AgentRunnerNode.
    pub fn new(factory: Arc<AgentFactory>) -> Self {
        Self {
            factory,
            session_id_prefix: "graph".into(),
            model: None,
            max_turns: 100,
            profile_id: None,
            task_type: None,
            content_tx: None,
        }
    }

    /// Set the session ID prefix.
    pub fn with_session_prefix(mut self, prefix: impl Into<String>) -> Self {
        self.session_id_prefix = prefix.into();
        self
    }

    /// Set the model to use.
    pub fn with_model(mut self, model: impl Into<String>) -> Self {
        self.model = Some(model.into());
        self
    }

    /// Set the maximum turns.
    pub fn with_max_turns(mut self, max_turns: u32) -> Self {
        self.max_turns = max_turns;
        self
    }

    /// Set the profile ID for model routing.
    pub fn with_profile_id(mut self, profile_id: impl Into<String>) -> Self {
        self.profile_id = Some(profile_id.into());
        self
    }

    /// Set the task type hint.
    pub fn with_task_type(mut self, task_type: impl Into<String>) -> Self {
        self.task_type = Some(task_type.into());
        self
    }

    /// Set a content streaming channel for forwarding thinking/text tokens during execution.
    pub fn with_content_stream(
        mut self,
        tx: tokio::sync::mpsc::Sender<super::GraphStreamEvent>,
    ) -> Self {
        self.content_tx = Some(tx);
        self
    }
}

#[async_trait]
impl NodeHandler<AgentGraphState> for AgentRunnerNode {
    async fn execute(
        &self,
        mut state: AgentGraphState,
        ctx: &NodeContext,
    ) -> Result<AgentGraphState, NodeError> {
        // Mark execution start
        state.metadata.mark_start();

        // Create a unique session ID for this graph execution
        let session_id = format!(
            "{}-{}-{}",
            self.session_id_prefix, ctx.graph_execution_id, ctx.node_id
        );

        // R2-H12: Get or create agent from factory with per-node overrides including max_turns
        let agent_lock = self
            .factory
            .get_or_create_with_overrides(
                &session_id,
                self.model.clone(),
                self.profile_id.clone(),
                self.task_type.clone(),
                Some(self.max_turns),
            )
            .await;

        // Execute the agent query
        let mut agent = agent_lock.write().await;
        let mut stream = agent.query(&state.task).await;

        // Collect all messages from the stream
        while let Some(msg_result) = stream.next().await {
            // Check for cancellation
            if ctx.is_cancelled() {
                return Err(NodeError::Cancelled);
            }

            match msg_result {
                Ok(msg) => {
                    // Forward content blocks to SSE channel if streaming is enabled
                    if let Some(ref tx) = self.content_tx {
                        match &msg {
                            AgentMessage::Assistant(assistant_msg) => {
                                for block in &assistant_msg.content {
                                    let event = match block {
                                        crate::agent::ContentBlock::Thinking {
                                            thinking, ..
                                        } if !thinking.is_empty() => {
                                            Some(super::GraphStreamEvent::NodeThinking {
                                                execution_id: ctx.graph_execution_id.clone(),
                                                node_id: ctx.node_id.clone(),
                                                content: thinking.clone(),
                                            })
                                        }
                                        crate::agent::ContentBlock::Text { text }
                                            if !text.is_empty() =>
                                        {
                                            Some(super::GraphStreamEvent::NodeText {
                                                execution_id: ctx.graph_execution_id.clone(),
                                                node_id: ctx.node_id.clone(),
                                                content: text.clone(),
                                            })
                                        }
                                        crate::agent::ContentBlock::ToolUse {
                                            id, name, ..
                                        } => Some(super::GraphStreamEvent::NodeToolCall {
                                            execution_id: ctx.graph_execution_id.clone(),
                                            node_id: ctx.node_id.clone(),
                                            tool_id: id.clone(),
                                            tool_name: name.clone(),
                                        }),
                                        _ => None,
                                    };
                                    if let Some(evt) = event {
                                        let _ = tx.send(evt).await;
                                    }
                                }
                            }
                            AgentMessage::User(user_msg) => {
                                if user_msg.tool_use_result.is_some() {
                                    if let Some(parent_id) = &user_msg.parent_tool_use_id {
                                        let _ = tx
                                            .send(super::GraphStreamEvent::NodeToolResult {
                                                execution_id: ctx.graph_execution_id.clone(),
                                                node_id: ctx.node_id.clone(),
                                                tool_id: parent_id.clone(),
                                            })
                                            .await;
                                    }
                                }
                            }
                            _ => {}
                        }
                    }

                    // Extract usage from result messages
                    if let AgentMessage::Result(result_msg) = &msg {
                        if let Some(usage) = &result_msg.usage {
                            let model = state
                                .metadata
                                .models_used
                                .last()
                                .cloned()
                                .unwrap_or_else(|| "unknown".into());
                            state.metadata.record_usage(usage, &model);
                        }
                        if result_msg.is_error {
                            // Use result field as error message when is_error is true
                            if let Some(err_text) = &result_msg.result {
                                state.error = Some(err_text.clone());
                            } else {
                                state.error = Some("Unknown error".to_string());
                            }
                        }
                    }
                    // Track model from assistant messages
                    if let AgentMessage::Assistant(assistant_msg) = &msg {
                        if !state.metadata.models_used.contains(&assistant_msg.model) {
                            state.metadata.models_used.push(assistant_msg.model.clone());
                        }
                    }
                    state.add_message(msg);
                }
                Err(e) => {
                    state.metadata.mark_end();
                    return Err(NodeError::HandlerError(e.to_string()));
                }
            }
        }

        // Mark execution end
        state.metadata.mark_end();

        // Store result for this node
        state.set_step_result(
            &ctx.node_id,
            serde_json::json!({
                "response": state.response.clone(),
                "message_count": state.messages.len(),
                "duration_ms": state.metadata.duration_ms(),
            }),
        );

        Ok(state)
    }
}

/// A simple LLM call node that makes a single LLM request.
///
/// Unlike AgentRunnerNode which runs a full agent loop with tool execution,
/// this node makes a single LLM API call and returns the response.
pub struct LlmCallNode {
    /// The LLM router for making calls (route() takes &self, no lock needed).
    router: Arc<crate::llm::LlmRouter>,
    /// Model to use (if any).
    model: Option<String>,
    /// Profile ID for routing.
    profile_id: Option<String>,
    /// System prompt to prepend.
    system_prompt: Option<String>,
    /// Maximum tokens to generate.
    max_tokens: Option<u32>,
    /// Temperature for generation (defaults to 0.7 if not set).
    temperature: Option<f32>,
}

impl LlmCallNode {
    /// Create a new LLM call node.
    pub fn new(router: Arc<crate::llm::LlmRouter>) -> Self {
        Self {
            router,
            model: None,
            profile_id: None,
            system_prompt: None,
            max_tokens: None,
            temperature: None,
        }
    }

    /// Set the model to use.
    pub fn with_model(mut self, model: impl Into<String>) -> Self {
        self.model = Some(model.into());
        self
    }

    /// Set the profile ID for routing.
    pub fn with_profile_id(mut self, profile_id: impl Into<String>) -> Self {
        self.profile_id = Some(profile_id.into());
        self
    }

    /// Set the system prompt.
    pub fn with_system_prompt(mut self, prompt: impl Into<String>) -> Self {
        self.system_prompt = Some(prompt.into());
        self
    }

    /// Set the maximum tokens.
    pub fn with_max_tokens(mut self, max_tokens: u32) -> Self {
        self.max_tokens = Some(max_tokens);
        self
    }

    /// Set the temperature for generation.
    pub fn with_temperature(mut self, temperature: f32) -> Self {
        self.temperature = Some(temperature);
        self
    }
}

#[async_trait]
impl NodeHandler<AgentGraphState> for LlmCallNode {
    async fn execute(
        &self,
        mut state: AgentGraphState,
        ctx: &NodeContext,
    ) -> Result<AgentGraphState, NodeError> {
        use crate::llm::{ChatRequest, Message};

        state.metadata.mark_start();

        // Build messages
        let mut messages = Vec::new();
        if let Some(ref system_prompt) = self.system_prompt {
            messages.push(Message::text("system", system_prompt));
        }
        messages.push(Message::text("user", &state.task));

        // Build request
        let request = ChatRequest {
            messages,
            model: self.model.clone(),
            max_tokens: self.max_tokens,
            temperature: Some(self.temperature.unwrap_or(0.7)),
            stream: false,
            ..Default::default()
        };

        // Make the LLM call
        let response = self
            .router
            .route(request)
            .await
            .map_err(|e| NodeError::HandlerError(format!("LLM call failed: {}", e)))?;

        // Extract response content
        let content = response
            .choices
            .first()
            .map(|c| c.message.content.clone())
            .ok_or_else(|| NodeError::HandlerError("LLM returned empty choices".to_string()))?;

        // Update state
        state.response = content;
        state.metadata.total_tokens +=
            (response.usage.prompt_tokens + response.usage.completion_tokens) as u32;
        if !state.metadata.models_used.contains(&response.model) {
            state.metadata.models_used.push(response.model.clone());
        }

        state.metadata.mark_end();

        // Store result
        state.set_step_result(
            &ctx.node_id,
            serde_json::json!({
                "response": state.response.clone(),
                "model": response.model,
                "tokens": response.usage.total_tokens,
            }),
        );

        Ok(state)
    }
}

/// A node that executes a single tool call.
///
/// This is useful for graph workflows that need to call specific tools
/// as part of their execution (e.g., always read a file, always search).
pub struct ToolCallNode {
    /// The tool registry.
    registry: Arc<crate::agent::tools::ToolRegistry>,
    /// Name of the tool to call.
    tool_name: String,
    /// Key in working_memory where tool input is stored.
    input_memory_key: String,
    /// Key in working_memory where tool output will be stored.
    output_memory_key: String,
}

impl ToolCallNode {
    /// Create a new tool call node.
    pub fn new(
        registry: Arc<crate::agent::tools::ToolRegistry>,
        tool_name: impl Into<String>,
    ) -> Self {
        let tool_name = tool_name.into();
        Self {
            registry,
            input_memory_key: format!("{}_input", tool_name),
            output_memory_key: format!("{}_output", tool_name),
            tool_name,
        }
    }

    /// Set the input memory key.
    pub fn with_input_key(mut self, key: impl Into<String>) -> Self {
        self.input_memory_key = key.into();
        self
    }

    /// Set the output memory key.
    pub fn with_output_key(mut self, key: impl Into<String>) -> Self {
        self.output_memory_key = key.into();
        self
    }
}

#[async_trait]
impl NodeHandler<AgentGraphState> for ToolCallNode {
    async fn execute(
        &self,
        mut state: AgentGraphState,
        ctx: &NodeContext,
    ) -> Result<AgentGraphState, NodeError> {
        use crate::agent::tools::ToolContext;

        // Get tool input from working memory
        let input = state
            .get_memory(&self.input_memory_key)
            .cloned()
            .unwrap_or_else(|| serde_json::json!({}));

        // Create tool context using the builder pattern
        let cwd = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
        let tool_ctx = ToolContext::new(ctx.graph_execution_id.clone(), cwd);

        // Execute the tool
        let result = self
            .registry
            .execute(&self.tool_name, input.clone(), &tool_ctx)
            .await
            .map_err(|e| {
                NodeError::HandlerError(format!("Tool {} failed: {}", self.tool_name, e))
            })?;

        // Store output in working memory
        state.set_memory(&self.output_memory_key, result.clone());

        // Store result for this node
        state.set_step_result(
            &ctx.node_id,
            serde_json::json!({
                "tool": self.tool_name,
                "input": input,
                "output": result,
            }),
        );

        Ok(state)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_agent_graph_state_creation() {
        let state = AgentGraphState::new("Test task");
        assert_eq!(state.task, "Test task");
        assert!(state.messages.is_empty());
        assert!(state.response.is_empty());
        assert!(!state.has_error());
    }

    #[test]
    fn test_agent_graph_state_memory() {
        let mut state = AgentGraphState::new("task");
        state.set_memory("key1", serde_json::json!({"value": 42}));
        assert_eq!(
            state.get_memory("key1"),
            Some(&serde_json::json!({"value": 42}))
        );
        assert_eq!(state.get_memory("nonexistent"), None);
    }

    #[test]
    fn test_agent_graph_state_step_results() {
        let mut state = AgentGraphState::new("task");
        state.set_step_result("step1", serde_json::json!("result1"));
        assert_eq!(
            state.get_step_result("step1"),
            Some(&serde_json::json!("result1"))
        );
    }

    #[test]
    fn test_agent_graph_state_error() {
        let state = AgentGraphState::new("task").with_error("Something went wrong");
        assert!(state.has_error());
        assert_eq!(state.error, Some("Something went wrong".to_string()));
    }

    #[test]
    fn test_agent_graph_state_merge() {
        let mut state1 = AgentGraphState::new("task1");
        state1.response = "Hello".into();
        state1.metadata.total_tokens = 100;
        state1.set_step_result("step1", serde_json::json!("r1"));

        let mut state2 = AgentGraphState::new("task2");
        state2.response = "World".into();
        state2.metadata.total_tokens = 50;
        state2.set_step_result("step2", serde_json::json!("r2"));

        state1.merge(state2);

        assert_eq!(state1.metadata.total_tokens, 150);
        assert_eq!(state1.response, "Hello\nWorld");
        assert!(state1.get_step_result("step1").is_some());
        assert!(state1.get_step_result("step2").is_some());
    }

    #[test]
    fn test_state_metadata() {
        let mut meta = StateMetadata::default();
        meta.mark_start();
        std::thread::sleep(std::time::Duration::from_millis(10));
        meta.mark_end();

        assert!(meta.started_at.is_some());
        assert!(meta.ended_at.is_some());
        // Duration should be non-negative (might be 0 due to second-level precision)
        assert!(meta.duration_ms().unwrap() >= 0);
    }

    #[test]
    fn test_agent_runner_node_builder() {
        // We can't easily test with a real factory, but we can test the builder pattern
        // This test is more of a compile-time check
        // let node = AgentRunnerNode::new(Arc::new(factory))
        //     .with_session_prefix("test")
        //     .with_model("claude-sonnet-4-5-20250929")
        //     .with_max_turns(50)
        //     .with_profile_id("default")
        //     .with_task_type("code");
    }
}
